<?php
// Generated by ZF2's ./bin/classmap_generator.php
$symfonyDir = dirname(__DIR__) . '/Vendor/Symfony';
$zendDir    = dirname(__DIR__) . '/Vendor/Zend';
return array(
	
	// PPI ClassMap
	'PPI\App'                                                   => __DIR__ . '/App.php',
	'PPI\Autoload'                                              => __DIR__ . '/Autoload.php',
	'PPI\Module\Module'                                         => __DIR__ . '/Module/Module.php',
	'PPI\Module\Controller'                                     => __DIR__ . '/Module/Controller.php',
	'PPI\Module\ServiceLocator'                                 => __DIR__ . '/Module/ServiceLocator.php',
	'PPI\Module\Templating\FileLocator'                         => __DIR__ . '/Module/Templating/FileLocator.php',
	'PPI\Module\Templating\TemplateLocator'                     => __DIR__ . '/Module/Templating/TemplateLocator.php',
	'PPI\Module\Templating\FileSystemLoader'                    => __DIR__ . '/Module/Templating/FileSystemLoader.php',
	'PPI\Module\Templating\TemplateReference'                   => __DIR__ . '/Module/Templating/TemplateReference.php',
	'PPI\Module\Routing\Loader\YamlFileLoader'                  => __DIR__ . '/Module/Routing/Loader/YamlFileLoader.php',
	'PPI\Module\Templating\TemplateNameParser'                  => __DIR__ . '/Module/Templating/TemplateNameParser.php',
	'PPI\Module\Listener\DefaultListenerAggregate'              => __DIR__ . '/Module/Listener/DefaultListenerAggregate.php',
	
	// Symfony ClassMap	
	'Symfony\Component\HttpFoundation\Request'                  => $symfonyDir . '/Component/HttpFoundation/Request.php',
	'Symfony\Component\HttpFoundation\FileBag'                  => $symfonyDir . '/Component/HttpFoundation/FileBag.php',
	'Symfony\Component\HttpFoundation\Response'                 => $symfonyDir . '/Component/HttpFoundation/Response.php',
	'Symfony\Component\HttpFoundation\ServerBag'                => $symfonyDir . '/Component/HttpFoundation/ServerBag.php',
	'Symfony\Component\HttpFoundation\HeaderBag'                => $symfonyDir . '/Component/HttpFoundation/HeaderBag.php',
	'Symfony\Component\HttpFoundation\ParameterBag'             => $symfonyDir . '/Component/HttpFoundation/ParameterBag.php',
	'Symfony\Component\HttpFoundation\ResponseHeaderBag'        => $symfonyDir . '/Component/HttpFoundation/ResponseHeaderBag.php',
	
	'Symfony\Component\Config\FileLocator'                      => $symfonyDir . '/Component/Config/FileLocator.php',
	'Symfony\Component\Config\Loader\Loader'                    => $symfonyDir . '/Component/Config/Loader/Loader.php',
	'Symfony\Component\Config\Loader\FileLoader'                => $symfonyDir . '/Component/Config/Loader/FileLoader.php',
	'Symfony\Component\Config\FileLocatorInterface'             => $symfonyDir . '/Component/Config/FileLocatorInterface.php',
	'Symfony\Component\Config\Resource\FileResource'            => $symfonyDir . '/Component/Config/Resource/FileResource.php',
	'Symfony\Component\Config\Loader\LoaderInterface'           => $symfonyDir . '/Component/Config/Loader/LoaderInterface.php',
	'Symfony\Component\Config\Resource\ResourceInterface'       => $symfonyDir . '/Component/Config/Resource/ResourceInterface.php',

	'Symfony\Component\Templating\PhpEngine'                    => $symfonyDir . '/Component/Templating/PhpEngine.php',
	'Symfony\Component\Templating\Helper\Helper'                => $symfonyDir . '/Component/Templating/Helper/Helper.php',
	'Symfony\Component\Templating\Storage\Storage'              => $symfonyDir . '/Component/Templating/Storage/Storage.php',
	'Symfony\Component\Templating\EngineInterface'              => $symfonyDir . '/Component/Templating/EngineInterface.php',
	'Symfony\Component\Templating\TemplateReference'            => $symfonyDir . '/Component/Templating/TemplateReference.php',
	'Symfony\Component\Templating\Helper\SlotsHelper'           => $symfonyDir . '/Component/Templating/Helper/SlotsHelper.php',
	'Symfony\Component\Templating\TemplateNameParser'           => $symfonyDir . '/Component/Templating/TemplateNameParser.php',
	'Symfony\Component\Templating\Storage\FileStorage'          => $symfonyDir . '/Component/Templating/Storage/FileStorage.php',
	'Symfony\Component\Templating\Helper\HelperInterface'       => $symfonyDir . '/Component/Templating/Helper/HelperInterface.php',
	'Symfony\Component\Templating\Loader\LoaderInterface'       => $symfonyDir . '/Component/Templating/Loader/LoaderInterface.php',
	'Symfony\Component\Templating\TemplateReferenceInterface'   => $symfonyDir . '/Component/Templating/TemplateReferenceInterface.php',
	'Symfony\Component\Templating\TemplateNameParserInterface'  => $symfonyDir . '/Component/Templating/TemplateNameParserInterface.php',
	
	'Symfony\Component\Routing\Route'                           => $symfonyDir . '/Component/Routing/Route.php',
	'Symfony\Component\Routing\RouteCompiler'                   => $symfonyDir . '/Component/Routing/RouteCompiler.php',
	'Symfony\Component\Routing\CompiledRoute'                   => $symfonyDir . '/Component/Routing/CompiledRoute.php',
	'Symfony\Component\Routing\RequestContext'                  => $symfonyDir . '/Component/Routing/RequestContext.php',
	'Symfony\Component\Routing\RouteCollection'                 => $symfonyDir . '/Component/Routing/RouteCollection.php',
	'Symfony\Component\Routing\Matcher\UrlMatcher'              => $symfonyDir . '/Component/Routing/Matcher/UrlMatcher.php',
	'Symfony\Component\Routing\Loader\YamlFileLoader'           => $symfonyDir . '/Component/Routing/Loader/YamlFileLoader.php',
	'Symfony\Component\Routing\Generator\UrlGenerator'          => $symfonyDir . '/Component/Routing/Generator/UrlGenerator.php',
	'Symfony\Component\Routing\RouteCompilerInterface'          => $symfonyDir . '/Component/Routing/RouteCompilerInterface.php',
	'Symfony\Component\Routing\Matcher\UrlMatcherInterface'     => $symfonyDir . '/Component/Routing/Matcher/UrlMatcherInterface.php',
	'Symfony\Component\Routing\RequestContextAwareInterface'    => $symfonyDir . '/Component/Routing/RequestContextAwareInterface.php',
	'Symfony\Component\Routing\Generator\UrlGeneratorInterface' => $symfonyDir . '/Component/Routing/Generator/UrlGeneratorInterface.php',

	'Symfony\Component\Yaml\Yaml'                               => $symfonyDir . '/Component/Yaml/Yaml.php',
	'Symfony\Component\Yaml\Parser'                             => $symfonyDir . '/Component/Yaml/Parser.php',
	'Symfony\Component\Yaml\Inline'                             => $symfonyDir . '/Component/Yaml/Inline.php',
	'Symfony\Component\Yaml\Unescaper'                          => $symfonyDir . '/Component/Yaml/Unescaper.php',
 
	// Zend ClassMap
	'Zend\Module\Manager'                                       => $zendDir . '/Module/Manager.php',
	'Zend\Module\ModuleEvent'                                   => $zendDir . '/Module/ModuleEvent.php',
	'Zend\Module\ModuleHandler'                                 => $zendDir . '/Module/ModuleHandler.php',
	'Zend\Module\Listener\InitTrigger'                          => $zendDir . '/Module/Listener/InitTrigger.php',
	'Zend\Module\Listener\ConfigMerger'                         => $zendDir . '/Module/Listener/ConfigMerger.php',
	'Zend\Module\Listener\ListenerOptions'                      => $zendDir . '/Module/Listener/ListenerOptions.php',
	'Zend\Module\Listener\ConfigListener'                       => $zendDir . '/Module/Listener/ConfigListener.php',
	'Zend\Module\Listener\AbstractListener'                     => $zendDir . '/Module/Listener/AbstractListener.php',
	'Zend\Module\Listener\AutoloaderListener'                   => $zendDir . '/Module/Listener/AutoloaderListener.php',
	'Zend\Module\Listener\ModuleResolverListener'               => $zendDir . '/Module/Listener/ModuleResolverListener.php',
	'Zend\Module\Listener\DefaultListenerAggregate'             => $zendDir . '/Module/Listener/DefaultListenerAggregate.php',
	'Zend\Module\Listener\LocatorRegistrationListener'          => $zendDir . '/Module/Listener/LocatorRegistrationListener.php',

	'Zend\EventManager\Event'                                   => $zendDir . '/EventManager/Event.php',
	'Zend\EventManager\EventManager'                            => $zendDir . '/EventManager/EventManager.php',
	'Zend\EventManager\ModuleHandler'                           => $zendDir . '/EventManager/ModuleHandler.php',
	'Zend\EventManager\EventCollection'                         => $zendDir . '/EventManager/EventCollection.php',
	'Zend\EventManager\EventDescription'                        => $zendDir . '/EventManager/EventDescription.php',
	'Zend\EventManager\ListenerAggregate'                       => $zendDir . '/EventManager/ListenerAggregate.php',
	'Zend\EventManager\ResponseCollection'                      => $zendDir . '/EventManager/ResponseCollection.php',
	'Zend\EventManager\StaticEventManager'                      => $zendDir . '/EventManager/StaticEventManager.php',
	'Zend\EventManager\StaticEventCollection'                   => $zendDir . '/EventManager/StaticEventCollection.php',
	
	'Zend\Stdlib\Options'                                       => $zendDir . '/Stdlib/Options.php',
	'Zend\Stdlib\PriorityQueue'                                 => $zendDir . '/Stdlib/PriorityQueue.php',
	'Zend\Stdlib\CallbackHandler'                               => $zendDir . '/Stdlib/CallbackHandler.php',
	'Zend\Stdlib\ParameterObject'                               => $zendDir . '/Stdlib/ParameterObject.php',
	'Zend\Stdlib\SplPriorityQueue'                              => $zendDir . '/Stdlib/SplPriorityQueue.php',
	
	'Zend\Loader\SplAutoloader'                                 => $zendDir . '/Loader/SplAutoloader.php',
	'Zend\Loader\ModuleAutoloader'                              => $zendDir . '/Loader/ModuleAutoloader.php'
);